theme: jekyll-theme-cayman
title: "[워크샵] IT 업계 여성을 위한 내 이력서 웹 사이트 만들기"
description: "[위민 후 코드 서울]는 IT분야의 여성들의 경력개발을 위한 글로벌 네트워크입니다. 경력개발의 첫 걸음은 자신의 경력을 객관적으로 파악하고, 이를 잘 알리는 데에 있습니다. 많은 여성분들이 쑥스러워 하는 부분이기도 합니다. 함께 나의 경력을 객관적으로 파악하고, 성장을 위한 준비를 합시다. 
"